#%RAML 1.0
title: Ejemplo de uso de características resourceType y traits.
baseUri: http://www.example-traits-com/{version}
version: v1
mediaType: application/json
types: 
    Libro:
        type: object
        description: Objeto que describe a un libro.
        properties:
            titulo:
                type: string
                minLength: 3
            autor:
                type: string
                minLength: 3
            editorial:
                type: string
    Usuario:
        type: object
        description: Objeto que describe a un usuario.
        properties:
            nombre: string
            correo: string
            empresa: string
resourceTypes: 
    coleccion:
        usage: Usar este tipo de recurso para para representar una colección de elementos.
        description: Colección de <<typeName>> disponibles.
        get:
            description: Obtener una lista de <<resourcePathName>>
            responses:
                200:
                    body:
                        application/json:
                            type: <<typeName>>[] # Ejemplo: Libros
                            example: <<exampleCollection>>
        post:
            description: Crear un nuevo <<resourcePathName|!singularize>>
            body:
                type: <<typeName>> # Ejemplo: Libro
            responses:
                201:
                    body:
                        type: <<typeName>> # Ejemplo: Libro
                        example: <<exampleElement>>

/libros:
    type:
        coleccion:
            typeName: Libro
            exampleElement: !include examples/libros/libro.json
            exampleCollection: !include examples/libros/libros.json

/usuarios: #Otra forma de usar notacion para resourceTypes
    type: {coleccion: { typeName: Usuario, exampleElement: !include examples/usuarios/usuario.json, exampleCollection: !include examples/usuarios/usuarios.json}}
