#%RAML 1.0 DataType
type: object
properties:
    current-password:
        required: true
        type: string
        description: El password que tiene actualmente.
    new-password:
        required: true
        type: string
        description: El nuevo password a configurar.
    confirm-password:
        required: true
        type: string
        description: La confirmacion del nuevo password, debe coincidir con `new-password`
example:
    current-password: abc123
    new-password: s1231231
    confirm-password: s1231231
