#%RAML 1.0 DataType
#Se agregan caracteristicas a un objeto mediante su extension.
type: !include Respuesta.raml
properties:
    /^regla\d+$/: #Se definen propiedades con expresiones regulares. Aunque no es la mejor opcion.
        enum: [ ok, fail ]
